### ISSUE TITLE
Update Community Translation to v1.6.8

### ISSUE THREAD

**Issue by mlocati** [concretecms/translate.concretecms.org#100]
Since [I can't create a pull request that does that anymore](https://github.com/concretecms/translate.concretecms.org/pull/97#issuecomment-2377483691), could someone please update Community Translation to v1.6.8?

See the [changelog](https://github.com/concretecms/addon_community_translation/compare/1.6.7...1.6.8).

Ping @KorvinSzanto

**Comment by mlocati** [comment]
That new release is meant to check why I see this error in the logs:

```
Exception Occurred:
packages/community_translation/src/Translatable/StringFormat.php:23
3 arguments are required, 2 given
```

(I don't understand when and how that error may occur, and I need more details about it)

**Comment by KorvinSzanto** [comment]
This has been applied, thanks @mlocati
